-DARDUINO=1081
-I "C:/Program Files/Labcenter Electronics/Proteus 9 Professional/Tools/Arduino/hardware/arduino/avr/cores/arduino"
-I "C:/Program Files/Labcenter Electronics/Proteus 9 Professional/Tools/Arduino/hardware/arduino/avr/variants/mega"
-I "C:/Program Files/Labcenter Electronics/Proteus 9 Professional/Tools/Arduino/hardware/arduino/avr/libraries/Wire/src"
-I "C:/Users/gusta/Documents/Arduino/libraries/Keypad/src"
-I "C:/ProgramData/Labcenter Electronics/Proteus 9 Professional/VSM Studio/drivers/Arduino/NeoPixel"
-I "C:/ProgramData/Labcenter Electronics/Proteus 9 Professional/VSM Studio/drivers/Arduino/TimerThree"
-I "C:/Users/gusta/Documents/Arduino/libraries/DHT_sensor_library"

